version: '3.8'

services:
  postgres:
    container_name: evolution_postgres
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: evolution_db
      POSTGRES_USER: postgres  
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - evolution-net

  redis:
    container_name: evolution_redis
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - evolution-net

volumes:
  postgres_data:

networks:
  evolution-net:
    name: evolution-net
    driver: bridge